services:
  mysql:
    image: mysql:latest
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestionformacion
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    image: eureka
    ports:
     - "8761:8761"
    networks:
      - spring-network
    environment:
      - eureka.instance.hostname=discoveryserver
      - eureka.client.serviceUrl.defaultZone=http://discoveryserver:8761/eureka

  convocatoria:
    image: convocatoria
    container_name: convocatoria-container
    ports:
      - "8105:8105"
    environment:
      DB_HOST: mysql_database
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin
    networks:
      - spring-network
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./core-module/target/classes:/app/classes

  course:
    image: course
    container_name: course-container
    ports:
      - "8102:8102"
    environment:
      DB_HOST: mysql_database
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin
    networks:
      - spring-network
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./core-module/target/classes:/app/classes
  login:
    image: login
    container_name: login-container
    ports:
      - "8100:8100"
    environment:
      DB_HOST: mysql_database
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin
    networks:
      - spring-network
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./core-module/target/classes:/app/classes

  register:
    image: register
    container_name: register-container
    ports:
      - "8101:8101"
    environment:
      DB_HOST: mysql_database
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin
    networks:
      - spring-network
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./core-module/target/classes:/app/classes

  rol:
    image: rol
    container_name: rol-container
    ports:
      - "8104:8104"
    environment:
      DB_HOST: mysql_database
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin
    networks:
      - spring-network
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./core-module/target/classes:/app/classes

  usuario:
    image: usuario
    container_name: usuario-container
    ports:
      - "8103:8103"
    environment:
      DB_HOST: mysql_database
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin
    networks:
      - spring-network
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./core-module/target/classes:/app/classes
networks:
  spring-network:
    driver: bridge

volumes:
  mysql-volume:
