services:

  convocatoria-app:
    image: convocatoria-app
    container_name: convocatoria-container
    ports:
      - "8105:8105"
    networks:
      - spring-network
    depends_on:
      - mysql
    volumes:
      - ./core-module/target/classes:/app/classes

  course-app:
    image: course-app
    container_name: course-container
    ports:
      - "8102:8102"
    networks:
      - spring-network
    volumes:
      - ./core-module/target/classes:/app/classes

  login-app:
    image: login-app
    container_name: login-container
    ports:
      - "8100:8100"
    networks:
      - spring-network
    volumes:
      - ./core-module/target/classes:/app/classes

  register-app:
    image: register-app
    container_name: register-container
    ports:
      - "8101:8101"
    networks:
      - spring-network
    volumes:
      - ./core-module/target/classes:/app/classes

  rol-app:
    image: rol-app
    container_name: rol-container
    ports:
      - "8104:8104"
    networks:
      - spring-network
    volumes:
      - ./core-module/target/classes:/app/classes
  usuario-app:
    image: usuario-app
    container_name: usuario-container
    ports:
      - "8103:8103"
    networks:
      - spring-network
    volumes:
      - ./core-module/target/classes:/app/classes
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestionformacion
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  spring-network:

volumes:
  mysql-volume: