server:
  port: 8106

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: convocatoria-module
          uri: http://convocatoria-container:8105
          predicates:
            - Path=/convocatorias/**
        - id: course-module
          uri: http://course-container:8102
          predicates:
            - Path=/courses/**
        - id: login-module
          uri: http://login-container:8100
          predicates:
            - Path=/autentificacion/login
        - id: register-module
          uri: http://register-container:8101
          predicates:
            - Path=/autentificacion/registrar
        - id: rol-module
          uri: http://rol-container:8104
          predicates:
            - Path=/roles/**
        - id: usuario-module
          uri: http://usuario-container:8103
          predicates:
            - Path=/usuarios/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
