spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: course-module


  datasource:
    url: jdbc:mysql://mysql_database:3306/gestionformacion
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8102

gestionformacion:
  secreto:
    jwt: TkpwTVpaMTFpVTBHWktjV0Y5AL9JdFJra0ZxPVRlZTN2ZkJjR0hrYjAMRs1=
  tiempo:
    expiracion:
      jwt: 3600000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    port: 8761
